import { createAction } from "redux-act";
import { ChainId } from "../../constants";
export const fetchAllTokenListSaga = createAction("fetch all token list saga", (account, ChainId) => ({ account, ChainId }));
export const fetchTokenBalaneSaga = createAction("fetch token balance saga", (tokenAddress, ChainId) => ({ tokenAddress, ChainId }));
export const setTokenList = createAction("set token list", (tokens) => ({ tokens }));
export const fetchSelectedPairSaga = createAction("fetch selected pair saga", (token, type) => ({ token, type }));
export const setSelectedPair = createAction("set selected pair", (token, type) => ({ token, type }));
export const setSelectedPairPrice = createAction("set selected pair price", (price) => ({ price }));
export const setTokenPriceList = createAction("set price", (priceList) => ({ priceList }));
export const swapQuoteSaga = createAction("swap token quote saga", (orderType, account) => ({ orderType, account }));
export const setTransactionProgress = createAction("set transaction started", (transactionStatus) => ({ transactionStatus }));
export const initTransactionStatus = createAction("init transaction status");
export const setPairPrice = createAction("set pair price", (price) => ({ price }));
export const setOrderType = createAction("set order type", (orderType) => ({ orderType }));
export const fetchOrderConfigSaga = createAction("fetch order config saga", (orderDetail) => ({ orderDetail }));
export const confirmTransactionSaga = createAction("confirm transaction saga");
export const swapSelectedPair = createAction("swap selected pair");
export const initWallet = createAction("init wallet status");
export const setSellAmount = createAction("set sell amount", (sellAmount) => ({ sellAmount }));
export const setBuyAmount = createAction("set buy amount", (buyAmount) => ({ buyAmount }));
export const setTransactionData = createAction("set transaction data", (transactionData) => ({ transactionData }));
export const getTransactionsByAccountSaga = createAction("getTransactionsByAccountSaga", (account) => ({ account }));
export const setTransactionHistory = createAction("setTransactionHistory", (transactionHistory) => ({ transactionHistory }));